name: flutter_application_1
description: "A new Flutter project for MatchMate."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase & Backend
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.0
  # State Management
  provider: ^6.1.2
  # Local Storage
  shared_preferences: ^2.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

  fonts:
    - family: MatchMateFont
      fonts:
        - asset: assets/MatchMateFont-Regular.ttf
        - asset: assets/MatchMateFont-Bold.ttf
          weight: 700